CREATE OR REPLACE FUNCTION update_user_by_about_fullname(
  p_nickname CITEXT,
  p_about TEXT,
  p_fullname TEXT)

RETURNS TABLE(nickname CITEXT,
              email CITEXT,
              about TEXT,
              fullname TEXT)
AS
$BODY$
  BEGIN
    RETURN QUERY
        UPDATE users
        SET about = p_about, fullname = p_fullname
        WHERE users.nickname = p_nickname
        RETURNING users.nickname, users.email, users.about, users.fullname;
  END;
$BODY$
LANGUAGE plpgsql VOLATILE;