CREATE OR REPLACE FUNCTION get_forum_by_slug(p_slug CITEXT)
  RETURNS TABLE(forum_id INT,
                slug CITEXT,
                "user" CITEXT,
                title TEXT,
                threads INT,
                posts INT)
AS
$BODY$
  BEGIN
    RETURN QUERY SELECT f.forum_id, f.slug, f.user_nickname, f.title, f.threads, f.posts
    FROM forums f
    WHERE f.slug = p_slug;
  END;
$BODY$
LANGUAGE plpgsql VOLATILE;