CREATE OR REPLACE FUNCTION add_posts(
  p_thread_id INT,
  p_forum_id INT,
  p_user_id INT,
  p_parent_id INT,
  p_message TEXT,
  p_created TIMESTAMP WITH TIME ZONE,
  p_is_edited BOOLEAN)
RETURNS void AS
$BODY$
  BEGIN
    INSERT INTO posts (thread_id, forum_id, user_id, parent_id,
                       message, created, is_edited)
      VALUES (p_thread_id, p_forum_id, p_user_id, p_parent_id,
              p_message, p_created, p_is_edited);
  END;
$BODY$
LANGUAGE plpgsql VOLATILE;