CREATE OR REPLACE FUNCTION get_users_for_forum_desc(
    p_forum_id INT
)


RETURNS TABLE(nickname CITEXT,
              email CITEXT,
              about TEXT,
              fullname TEXT)
AS
$BODY$
BEGIN

  RETURN QUERY
  SELECT uf.user_nickname, uf.user_email, uf.user_about, uf.user_fullname
  FROM users_for_forum uf
  WHERE uf.forum_id = p_forum_id
  ORDER BY uf.user_nickname COLLATE "ucs_basic" DESC;

  END;
$BODY$
LANGUAGE plpgsql VOLATILE;